version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: Andrea
      RABBITMQ_DEFAULT_PASS: 1503
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - rabbitmq_network

volumes:
  rabbitmq_data: {}

networks:
  rabbitmq_network:
    driver: bridge
